### ISSUE TITLE
Unable to get vechaiui working with vite 

### ISSUE THREAD

**Issue by snxk** [vechai/vechaiui#15]
I followed the installation guide but still, it failed.

error:
```
 > node_modules/.pnpm/@vechaiui+alert@0.1.6_react@17.0.2/node_modules/@vechaiui/alert/dist/esm/index.js:1:33: error: No matching export in "node_modules/.pnpm/@vechaiui+alert@0.1.6_react@17.0.2/node_modules/@vechaiui/alert/dist/esm/alert.js" for import "AlertProps"
    1 │ import { Alert as InternalAlert, AlertProps, AlertCloseButton, AlertCloseButtonProps } from "./alert";
      ╵                                  ~~~~~~~~~~

 > node_modules/.pnpm/@vechaiui+alert@0.1.6_react@17.0.2/node_modules/@vechaiui/alert/dist/esm/index.js:1:63: error: No matching export in "node_modules/.pnpm/@vechaiui+alert@0.1.6_react@17.0.2/node_modules/@vechaiui/alert/dist/esm/alert.js" for import "AlertCloseButtonProps"
    1 │ import { Alert as InternalAlert, AlertProps, AlertCloseButton, AlertCloseButtonProps } from "./alert";
      ╵                                                                ~~~~~~~~~~~~~~~~~~~~~

 > node_modules/.pnpm/@vechaiui+avatar@0.1.6_react@17.0.2/node_modules/@vechaiui/avatar/dist/esm/index.js:1:35: error: No matching export in "node_modules/.pnpm/@vechaiui+avatar@0.1.6_react@17.0.2/node_modules/@vechaiui/avatar/dist/esm/avatar.js" for import "AvatarProps"
    1 │ import { Avatar as InternalAvatar, AvatarProps } from "./avatar";
      ╵                                    ~~~~~~~~~~~

 > node_modules/.pnpm/@vechaiui+avatar@0.1.6_react@17.0.2/node_modules/@vechaiui/avatar/dist/esm/index.js:2:22: error: No matching export in "node_modules/.pnpm/@vechaiui+avatar@0.1.6_react@17.0.2/node_modules/@vechaiui/avatar/dist/esm/avatar-group.js" for import "AvatarGroupProps"
    2 │ import { AvatarGroup, AvatarGroupProps } from "./avatar-group";
      ╵                       ~~~~~~~~~~~~~~~~

 > node_modules/.pnpm/@vechaiui+breadcrumb@0.1.5_react@17.0.2/node_modules/@vechaiui/breadcrumb/dist/esm/index.js:1:43: error: No matching export in "node_modules/.pnpm/@vechaiui+breadcrumb@0.1.5_react@17.0.2/node_modules/@vechaiui/breadcrumb/dist/esm/breadcrumb.js" for import "BreadcrumbProps"
    1 │ import { Breadcrumb as InternalBreadcrumb, BreadcrumbProps, BreadcrumbItem, BreadcrumbItemProps, Brea...
      ╵                                            ~~~~~~~~~~~~~~~

 > node_modules/.pnpm/@vechaiui+breadcrumb@0.1.5_react@17.0.2/node_modules/@vechaiui/breadcrumb/dist/esm/index.js:1:76: error: No matching export in "node_modules/.pnpm/@vechaiui+breadcrumb@0.1.5_react@17.0.2/node_modules/@vechaiui/breadcrumb/dist/esm/breadcrumb.js" for import "BreadcrumbItemProps"
    1 │ ...crumb, BreadcrumbProps, BreadcrumbItem, BreadcrumbItemProps, BreadcrumbLink, BreadcrumbLinkProps, ...
      ╵                                            ~~~~~~~~~~~~~~~~~~~

 > node_modules/.pnpm/@vechaiui+breadcrumb@0.1.5_react@17.0.2/node_modules/@vechaiui/breadcrumb/dist/esm/index.js:1:113: error: No matching export in "node_modules/.pnpm/@vechaiui+breadcrumb@0.1.5_react@17.0.2/node_modules/@vechaiui/breadcrumb/dist/esm/breadcrumb.js" for import "BreadcrumbLinkProps"
    1 │ ...m, BreadcrumbItemProps, BreadcrumbLink, BreadcrumbLinkProps, BreadcrumbSeparator, BreadcrumbSepara...
      ╵                                            ~~~~~~~~~~~~~~~~~~~

 > node_modules/.pnpm/@vechaiui+breadcrumb@0.1.5_react@17.0.2/node_modules/@vechaiui/breadcrumb/dist/esm/index.js:1:155: error: No matching export in "node_modules/.pnpm/@vechaiui+breadcrumb@0.1.5_react@17.0.2/node_modules/@vechaiui/breadcrumb/dist/esm/breadcrumb.js" for import "BreadcrumbSeparatorProps"
    1 │ ...dcrumbLink, BreadcrumbLinkProps, BreadcrumbSeparator, BreadcrumbSeparatorProps } from "./breadcrumb";
      ╵                                                          ~~~~~~~~~~~~~~~~~~~~~~~~

 > node_modules/.pnpm/@vechaiui+button@0.1.5_react@17.0.2/node_modules/@vechaiui/button/dist/esm/index.js:1:35: error: No matching export in "node_modules/.pnpm/@vechaiui+button@0.1.5_react@17.0.2/node_modules/@vechaiui/button/dist/esm/button.js" for import "ButtonProps"
    1 │ import { Button as InternalButton, ButtonProps } from "./button";
      ╵                                    ~~~~~~~~~~~

 > node_modules/.pnpm/@vechaiui+button@0.1.5_react@17.0.2/node_modules/@vechaiui/button/dist/esm/index.js:2:22: error: No matching export in "node_modules/.pnpm/@vechaiui+button@0.1.5_react@17.0.2/node_modules/@vechaiui/button/dist/esm/button-group.js" for import "ButtonGroupProps"
    2 │ import { ButtonGroup, ButtonGroupProps } from "./button-group";
      ╵                       ~~~~~~~~~~~~~~~~

 > node_modules/.pnpm/@vechaiui+button@0.1.5_react@17.0.2/node_modules/@vechaiui/button/dist/esm/index.js:3:21: error: No matching export in "node_modules/.pnpm/@vechaiui+button@0.1.5_react@17.0.2/node_modules/@vechaiui/button/dist/esm/icon-button.js" for import "IconButtonProps"
    3 │ import { IconButton, IconButtonProps } from "./icon-button";
      ╵                      ~~~~~~~~~~~~~~~

 > node_modules/.pnpm/@vechaiui+forms@0.1.5_react@17.0.2/node_modules/@vechaiui/forms/dist/esm/input/index.js:1:33: error: No matching export in "node_modules/.pnpm/@vechaiui+forms@0.1.5_react@17.0.2/node_modules/@vechaiui/forms/dist/esm/input/input.js" for import "InputProps"
    1 │ import { Input as InternalInput, InputProps } from "./input";
      ╵                                  ~~~~~~~~~~

 > node_modules/.pnpm/@vechaiui+forms@0.1.5_react@17.0.2/node_modules/@vechaiui/forms/dist/esm/input/index.js:2:21: error: No matching export in "node_modules/.pnpm/@vechaiui+forms@0.1.5_react@17.0.2/node_modules/@vechaiui/forms/dist/esm/input-group/index.js" for import "InputGroupProps"
    2 │ import { InputGroup, InputGroupProps } from "../input-group";
      ╵                      ~~~~~~~~~~~~~~~

 > node_modules/.pnpm/@vechaiui+forms@0.1.5_react@17.0.2/node_modules/@vechaiui/forms/dist/esm/input/index.js:3:42: error: No matching export in "node_modules/.pnpm/@vechaiui+forms@0.1.5_react@17.0.2/node_modules/@vechaiui/forms/dist/esm/input-addon/index.js" for import "InputAddonProps"
    3 │ import { InputLeftAddon, InputRightAddon, InputAddonProps } from "../input-addon";
      ╵                                           ~~~~~~~~~~~~~~~

 > node_modules/.pnpm/@vechaiui+forms@0.1.5_react@17.0.2/node_modules/@vechaiui/forms/dist/esm/input/index.js:4:46: error: No matching export in "node_modules/.pnpm/@vechaiui+forms@0.1.5_react@17.0.2/node_modules/@vechaiui/forms/dist/esm/input-element/index.js" for import "InputElementProps"
    4 │ import { InputLeftElement, InputRightElement, InputElementProps } from "../input-element";
      ╵                                               ~~~~~~~~~~~~~~~~~

 > node_modules/.pnpm/@vechaiui+checkbox@0.2.3_react-dom@17.0.2+react@17.0.2/node_modules/@vechaiui/checkbox/dist/esm/index.js:1:39: error: No matching export in "node_modules/.pnpm/@vechaiui+checkbox@0.2.3_react-dom@17.0.2+react@17.0.2/node_modules/@vechaiui/checkbox/dist/esm/checkbox.js" for import "CheckboxProps"
    1 │ import { Checkbox as InternalCheckbox, CheckboxProps } from "./checkbox";
      ╵                                        ~~~~~~~~~~~~~

 > node_modules/.pnpm/@vechaiui+checkbox@0.2.3_react-dom@17.0.2+react@17.0.2/node_modules/@vechaiui/checkbox/dist/esm/index.js:2:24: error: No matching export in "node_modules/.pnpm/@vechaiui+checkbox@0.2.3_react-dom@17.0.2+react@17.0.2/node_modules/@vechaiui/checkbox/dist/esm/checkbox-group.js" for import "CheckboxGroupProps"
    2 │ import { CheckboxGroup, CheckboxGroupProps } from "./checkbox-group";
      ╵                         ~~~~~~~~~~~~~~~~~~

 > node_modules/.pnpm/@vechaiui+radio@0.1.5_react-dom@17.0.2+react@17.0.2/node_modules/@vechaiui/radio/dist/esm/index.js:1:33: error: No matching export in "node_modules/.pnpm/@vechaiui+radio@0.1.5_react-dom@17.0.2+react@17.0.2/node_modules/@vechaiui/radio/dist/esm/radio.js" for import "RadioProps"
    1 │ import { Radio as InternalRadio, RadioProps } from "./radio";
      ╵                                  ~~~~~~~~~~

 > node_modules/.pnpm/@vechaiui+radio@0.1.5_react-dom@17.0.2+react@17.0.2/node_modules/@vechaiui/radio/dist/esm/index.js:2:21: error: No matching export in "node_modules/.pnpm/@vechaiui+radio@0.1.5_react-dom@17.0.2+react@17.0.2/node_modules/@vechaiui/radio/dist/esm/radio-group.js" for import "RadioGroupProps"
    2 │ import { RadioGroup, RadioGroupProps } from "./radio-group";
      ╵                      ~~~~~~~~~~~~~~~

 > node_modules/.pnpm/@vechaiui+tag@0.1.6_react@17.0.2/node_modules/@vechaiui/tag/dist/esm/index.js:1:29: error: No matching export in "node_modules/.pnpm/@vechaiui+tag@0.1.6_react@17.0.2/node_modules/@vechaiui/tag/dist/esm/tag.js" for import "TagProps"
    1 │ import { Tag as InternalTag, TagProps, TagCloseButton, TagCloseButtonProps, TagLabel, TagLabelProps }...
      ╵                              ~~~~~~~~

 > node_modules/.pnpm/@vechaiui+tag@0.1.6_react@17.0.2/node_modules/@vechaiui/tag/dist/esm/index.js:1:55: error: No matching export in "node_modules/.pnpm/@vechaiui+tag@0.1.6_react@17.0.2/node_modules/@vechaiui/tag/dist/esm/tag.js" for import "TagCloseButtonProps"
    1 │ ...s InternalTag, TagProps, TagCloseButton, TagCloseButtonProps, TagLabel, TagLabelProps } from "./tag";
      ╵                                             ~~~~~~~~~~~~~~~~~~~

 > node_modules/.pnpm/@vechaiui+tag@0.1.6_react@17.0.2/node_modules/@vechaiui/tag/dist/esm/index.js:1:86: error: No matching export in "node_modules/.pnpm/@vechaiui+tag@0.1.6_react@17.0.2/node_modules/@vechaiui/tag/dist/esm/tag.js" for import "TagLabelProps"
    1 │ ...s InternalTag, TagProps, TagCloseButton, TagCloseButtonProps, TagLabel, TagLabelProps } from "./tag";
      ╵                                                                            ~~~~~~~~~~~~~


12:13:27 PM [vite] error while updating dependencies:
Error: Build failed with 22 errors:
node_modules/.pnpm/@vechaiui+alert@0.1.6_react@17.0.2/node_modules/@vechaiui/alert/dist/esm/index.js:1:33: error: No matching export in "node_modules/.pnpm/@vechaiui+alert@0.1.6_react@17.0.2/node_modules/@vechaiui/alert/dist/esm/alert.js" for import "AlertProps"
node_modules/.pnpm/@vechaiui+alert@0.1.6_react@17.0.2/node_modules/@vechaiui/alert/dist/esm/index.js:1:63: error: No matching export in "node_modules/.pnpm/@vechaiui+alert@0.1.6_react@17.0.2/node_modules/@vechaiui/alert/dist/esm/alert.js" for import "AlertCloseButtonProps"
node_modules/.pnpm/@vechaiui+avatar@0.1.6_react@17.0.2/node_modules/@vechaiui/avatar/dist/esm/index.js:1:35: error: No matching export in "node_modules/.pnpm/@vechaiui+avatar@0.1.6_react@17.0.2/node_modules/@vechaiui/avatar/dist/esm/avatar.js" for import "AvatarProps"
node_modules/.pnpm/@vechaiui+avatar@0.1.6_react@17.0.2/node_modules/@vechaiui/avatar/dist/esm/index.js:2:22: error: No matching export in "node_modules/.pnpm/@vechaiui+avatar@0.1.6_react@17.0.2/node_modules/@vechaiui/avatar/dist/esm/avatar-group.js" for import "AvatarGroupProps"
node_modules/.pnpm/@vechaiui+breadcrumb@0.1.5_react@17.0.2/node_modules/@vechaiui/breadcrumb/dist/esm/index.js:1:43: error: No matching export in "node_modules/.pnpm/@vechaiui+breadcrumb@0.1.5_react@17.0.2/node_modules/@vechaiui/breadcrumb/dist/esm/breadcrumb.js" for import "BreadcrumbProps"
...
    at failureErrorWithLog (/home/snxk/Projects/react-playground/node_modules/.pnpm/esbuild@0.12.15/node_modules/esbuild/lib/main.js:1449:15)
    at /home/snxk/Projects/react-playground/node_modules/.pnpm/esbuild@0.12.15/node_modules/esbuild/lib/main.js:1131:28
    at runOnEndCallbacks (/home/snxk/Projects/react-playground/node_modules/.pnpm/esbuild@0.12.15/node_modules/esbuild/lib/main.js:921:63)
    at buildResponseToResult (/home/snxk/Projects/react-playground/node_modules/.pnpm/esbuild@0.12.15/node_modules/esbuild/lib/main.js:1129:7)
    at /home/snxk/Projects/react-playground/node_modules/.pnpm/esbuild@0.12.15/node_modules/esbuild/lib/main.js:1236:14
    at /home/snxk/Projects/react-playground/node_modules/.pnpm/esbuild@0.12.15/node_modules/esbuild/lib/main.js:609:9
    at handleIncomingPacket (/home/snxk/Projects/react-playground/node_modules/.pnpm/esbuild@0.12.15/node_modules/esbuild/lib/main.js:706:9)
    at Socket.readFromStdout (/home/snxk/Projects/react-playground/node_modules/.pnpm/esbuild@0.12.15/node_modules/esbuild/lib/main.js:576:7)
    at Socket.emit (node:events:394:28)
    at Socket.emit (node:domain:470:12)
```

**Comment by pepelele** [comment]
Seems like export type error, I will fix it soon

**Comment by pepelele** [comment]
@snxk It should work with the latest version now
